// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZIB61AKvRIFDD4UksbFBirfALMud7xrE',
    appId: '1:550983757478:web:6df7dd7e3f9fe54322ce67',
    messagingSenderId: '550983757478',
    projectId: 'site-sync-c8a63',
    authDomain: 'site-sync-c8a63.firebaseapp.com',
    storageBucket: 'site-sync-c8a63.appspot.com',
    measurementId: 'G-J1N07BBXEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ2pHvzxtoqUaH9HbqGX0946U-8BSOhuI',
    appId: '1:550983757478:android:1d375db7b373394122ce67',
    messagingSenderId: '550983757478',
    projectId: 'site-sync-c8a63',
    storageBucket: 'site-sync-c8a63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqKKtD1ECMZVVwNEA_ONi59DWzOaQ1FJM',
    appId: '1:550983757478:ios:5c8f64da14d55d0922ce67',
    messagingSenderId: '550983757478',
    projectId: 'site-sync-c8a63',
    storageBucket: 'site-sync-c8a63.appspot.com',
    androidClientId: '550983757478-qe8eh12onqqmp04nbf1tokkhrju704vm.apps.googleusercontent.com',
    iosClientId: '550983757478-mk4lo5sa9orhhevd2o71b1pfm41en4eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.amirKhan1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqKKtD1ECMZVVwNEA_ONi59DWzOaQ1FJM',
    appId: '1:550983757478:ios:58b23a12a0c853f522ce67',
    messagingSenderId: '550983757478',
    projectId: 'site-sync-c8a63',
    storageBucket: 'site-sync-c8a63.appspot.com',
    androidClientId: '550983757478-qe8eh12onqqmp04nbf1tokkhrju704vm.apps.googleusercontent.com',
    iosClientId: '550983757478-rjgvo4p8nsodrom4irooh6rrusb1kat3.apps.googleusercontent.com',
    iosBundleId: 'com.example.amirKhan1.RunnerTests',
  );
}
