// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDSfRFfn4bADfx9J_rR4MFvqPVKyL1tMM',
    appId: '1:375912681943:web:acf6c90ebc7d6eee1f3b92',
    messagingSenderId: '375912681943',
    projectId: 'site-sync-381af',
    authDomain: 'site-sync-381af.firebaseapp.com',
    storageBucket: 'site-sync-381af.appspot.com',
    measurementId: 'G-6B1C1G4FPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClGWjE1hPWtg9qob4sn47x2SwfG81KFhU',
    appId: '1:375912681943:android:8345fccb92a073951f3b92',
    messagingSenderId: '375912681943',
    projectId: 'site-sync-381af',
    storageBucket: 'site-sync-381af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9iw4uhL29GTwyRu3SlGoMgYwMVUkpIqI',
    appId: '1:375912681943:ios:a5fb38ad9cbac1f81f3b92',
    messagingSenderId: '375912681943',
    projectId: 'site-sync-381af',
    storageBucket: 'site-sync-381af.appspot.com',
    iosBundleId: 'com.example.amirKhan1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9iw4uhL29GTwyRu3SlGoMgYwMVUkpIqI',
    appId: '1:375912681943:ios:c4c6c58b872e3d4c1f3b92',
    messagingSenderId: '375912681943',
    projectId: 'site-sync-381af',
    storageBucket: 'site-sync-381af.appspot.com',
    iosBundleId: 'com.example.amirKhan1.RunnerTests',
  );
}
